apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: mini
data:
  index.html: |
    <html>
      <body style="font-family:sans-serif;">
        <h1>Hi THis is rishi</h1>
        <p>If you edit this in Git, Rafay GitOps will deploy it.</p>
      </body>
    </html>
