name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - ".github/workflows/docker-build-push.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag (short SHA)
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ "rishikeshreddyv" }}
          password: ${{ "dckr_pat_3lQE-EN8Jd8cCbyp6L0CpUbCYkY" }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ "rishikeshreddyv" }}/mini-web:${{ env.TAG }}